### ISSUE TITLE
Misses SALTSpecError

### ISSUE THREAD

**Issue by crawfordsm** [crawfordsm/zSALT#7]
SALTSpecError, was not defined in MASTER/zsalt/spectools.py

**Comment by crawfordsm** [comment]
@hlabathems can you fix this?

**Comment by hlabathems** [comment]
It was missing the following:

class SALTSpecError(SaltError):
    """Errors involving Spec package should cause this exception to be raised."""
    pass

**Comment by crawfordsm** [comment]
This seems to have been closed by the updates to the code.
